### ISSUE TITLE
Lastest Update Blocker for firmware 4.55 creates a wrong folder

### ISSUE THREAD

**Issue by doctahoo** [LightningMods/PS4-4.55-Update-Blocker-FTP#3]
Hi, again,

I have just tried your latest update blocker for firmware 4.55, but I have noticed a small issue:

It creates both folders, as in the old payload version for 4.05, but one of the folder names is now wrong.

Your new payload creates **PS4UPDATE.temp.net** instead of **PS4UPDATE.net.temp**. As a result, the latest update is downloaded! (even if it cannot be installed).

Could you please check and fix this folder name at your earliest convenience?

Thank you in advance and keep up the good work!

**Comment by LightningMods** [comment]
It was already Solved in v3.1 ... refer back to the changelog
